### ISSUE TITLE
Clarification request: how to use OWNER only resolvers?

### ISSUE THREAD

**Issue by OndrejSpanel** [djspiewak/sbt-github-packages#21] opened 2020-04-21 08:06 UTC
I was excited to learn about the possibility of using the OWNER only resolver 

```resolvers += Resolver.githubPackages("OWNER")```

I am unable to get it working unfortunately. I have a public organization at https://github.com/OpenGrabeso. The organization has currently one repository dedicated to packages, which is https://github.com/OpenGrabeso/packages (more or less the same as you have described in https://github.community/t5/GitHub-Actions/Fundamental-Issues-with-Maven-Packages-and-how-to-address-them/td-p/47658). 

The error I get when doing `update` in sbt is:

```
not found: D:\Users\Ondra\.ivy2\local\org.jogamp.glg2d\glg2d\0.5.1-opengrabeso\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://maven.pkg.github.com/gamatron/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom (Server returned HTTP response code: 400 for URL: https://maven.pkg.github.com/gamatron/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom) while downloading https://maven.pkg.github.com/gamatron/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://maven.pkg.github.com/OpenGrabeso/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom (Server returned HTTP response code: 400 for URL: https://maven.pkg.github.com/OpenGrabeso/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom) while downloading https://maven.pkg.github.com/OpenGrabeso/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom
```

I am afraid there is some complication somewhere, something which is required and satisfied on yur setup but not for me. Do you have some idea how to proceed with identifying the problem?

**Comment by djspiewak** [comment] 2020-04-21 17:40
It looks to me like an authentication issue! Are you sure your token has the `read: package` grant?

**Comment by OndrejSpanel** [comment] 2020-04-21 19:44
Yes, the token has The same token works with `Resolver.githubPackages("OpenGrabeso"."packages")` fine.

**Comment by djspiewak** [comment] 2020-04-21 20:14
Looking at the groupId you're trying to resolve (`org.jogamp.glg2d`) and also looking at the package listing on the repository in question, the package doesn't appear to be present in the linked repo. Is it published in some other repository under one of those two organizations? If you can link me to a published package which resolves with the two-argument version but not the one-argument version, I should be able to narrow down what is causing this.

**Comment by OndrejSpanel** [comment] 2020-04-21 20:19
The package I have mentioned is https://github.com/OpenGrabeso/packages/packages/137005

**Comment by djspiewak** [comment] 2020-04-21 20:20
Odd that I didn't see it. Attempting to resolve…

**Comment by djspiewak** [comment] 2020-04-21 20:25
That resolved just fine for me with the following build file:

```sbt
resolvers += Resolver.githubPackages("OpenGrabeso")

libraryDependencies += "org.jogamp.glg2d" % "glg2d" % "0.5.1-opengrabeso"
```

Can you try running the following?

```bash
$ curl -vvv -L https://_:$(git config github.token)@maven.pkg.github.com/OpenGrabeso/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom
```

**Comment by OndrejSpanel** [comment] 2020-04-21 20:33
When I execute that, I get:

```
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 21 Apr 2020 20:31:39 GMT
< Content-Type: text/html; charset=utf-8
```

and the POM follows and look fine.

**Comment by djspiewak** [comment] 2020-04-21 20:36
So it's not an authentication or http thing, nor is it anything specific to this package or your account. Is it possible that your sbt is configured with some strange proxy settings or similar? Have you checked your global configurations? Also what version of sbt?

**Comment by OndrejSpanel** [comment] 2020-04-21 20:39
SBT is 1.3.8. I do not use any proxy. As for the global configuration, I am afraid I am not sure what you mean. Global configuration of what?

My system is Windows 10 x64, SBT running on Java 8.

**Comment by djspiewak** [comment] 2020-04-21 20:46
Windows directly (i.e. `cmd.exe`), `gitbash.exe`, or WSL?

**Comment by OndrejSpanel** [comment] 2020-04-21 20:47
I use mostly IntelliJ IDE, but am sometimes also testing from cmd or gitbash.

**Comment by djspiewak** [comment] 2020-04-21 21:02
Your global config is in `~/.sbt` and it's basically a bunch of build overrides that apply across all of your builds. It tends to be used for things like credentials. That might be where the issue is.

Also I just tried my test build on Windows and it worked just fine. Can you try grabbing this project and testing with it specifically? https://www.dropbox.com/s/lf7kw8s1q43wua5/test.zip?dl=1

**Comment by OndrejSpanel** [comment] 2020-04-21 21:06
The output of `update` in sbt from gitbash is:

```
sbt:test> update
[warn] undefined keys `githubOwner` and `githubRepository`
[warn] retaining pre-existing publication settings
[warn]
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run 'last update' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.jogamp.glg2d:glg2d:0.5.1-opengrabeso
[error]   Not found
[error]   Not found
[error]   not found: D:\Users\Ondra\.ivy2\local\org.jogamp.glg2d\glg2d\0.5.1-opengrabeso\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://maven.pkg.github.com/OpenGrabeso/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom (Server returned HTTP response code: 400 for URL: https://maven.pkg.github.com/OpenGrabeso/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom) while downloading https://maven.pkg.github.com/OpenGrabeso/_/org/jogamp/glg2d/glg2d/0.5.1-opengrabeso/glg2d-0.5.1-opengrabeso.pom
[error] Total time: 2 s, completed 21. 4. 2020 23:04:53

```

**Comment by OndrejSpanel** [comment] 2020-04-21 21:10
To be 100 % about the token I have freshly created a new one with scopes `delete:packages, read:packages, repo, write:packages`, still the same result.

**Comment by djspiewak** [comment] 2020-04-21 21:28
Something's definitely very very strange with your sbt setup then, and I don't understand what it is. Are you sure your `~/.sbt/1.0/` directory doesn't have anything in it? Look for any `.sbt` files recursively under that path.

The fact that it works in `curl` implies that there's nothing specific about your network connection, your token, or the repository, and I proved that that project works fine in Windows and macOS with those artifacts. Sbt itself is basically the only thing we haven't been able to rule out.

**Comment by OndrejSpanel** [comment] 2020-04-21 21:34
There is some .idea stuff in `~/.sbt/1.0/plugins` and a plugin `sbt-dependency-graph`. Even removing them all makes no difference. Other than that, the preferences folders are empty and there are some other folders called zinc, templates, staging and swoval-jni, which I have only a rough idea what they are, therefore I am unable to verify they contain what they should.

**Comment by OndrejSpanel** [comment] 2020-04-21 21:42
I am afraid I have to give up, at least for today. Thanks for your effort (and for your work on this plugin).

**Comment by djspiewak** [comment] 2020-04-21 21:47
Sorry :-( I'm really uncertain as to why this is happening. If you have access to another machine (or vmware) it's probably worth trying the test project there as well. It really does seem like an environmental thing, but I just don't understand where it could be coming from (note that the test project uses the `GITHUB_TOKEN` envar).

**Comment by OndrejSpanel** [comment] 2020-04-21 21:52
Ooooooo. That makes the test project clear. I only had some dummy string as `GITHUB_TOKEN` envar before.

Your test project now works for me fine. I think it worked with the `Resolver.githubPackages("OpenGrabeso","packages")` with the bad token because the artifact was already cached from that location.

**Comment by OndrejSpanel** [comment] 2020-04-21 21:54
I think this should be enough to get me moving. 

> It looks to me like an authentication issue

Most likely is was more or less the same as #20, again hidden by the fact the packages were already downloading. 

I will confirm tomorrow.

**Comment by djspiewak** [comment] 2020-04-21 23:21
This makes the world of sense! I didn’t even think about the token source. Also worth noting that a junk value in one token source (as opposed to just being undefined) will short circuit the || in your token source definition, resulting in an authentication error. This is because tokens are resolved and committed fully before we talk to the server (due to architectural limitations in sbt).

**Closed** 2022-01-23 16:57 UTC
